function scr_roomname(arg0)
{
	roomname = stringsetloc("Dark World?", "scr_roomname_slash_scr_roomname_gml_1_0")
	
	if scr_debug()
	    roomname = room_get_name(arg0)
	
	if (arg0 == room_gms_debug_failsafe)
		roomname = stringsetloc("---", "scr_roomname_slash_scr_roomname_gml_2_0")
	if (arg0 == room_krisroom)
		roomname = stringsetloc("Kris's Room", "scr_roomname_slash_scr_roomname_gml_4_0_b")
	if (arg0 == room_town_mid)
		roomname = stringsetloc("Hometown", "scr_roomname_slash_scr_roomname_gml_5_0_b")
	if (arg0 == room_lw_noellehouse_kitchen)
		roomname = stringsetloc("Noelle's House", "scr_roomname_slash_scr_roomname_gml_6_0")
	if (arg0 == room_dw_castle_town)
		roomname = stringsetloc("My Castle Town", "scr_roomname_slash_scr_roomname_gml_5_0")
	var church_name_a = stringsetloc("Dark Sanctuary", "scr_roomname_slash_scr_roomname_gml_7_0_b")
	if (arg0 == room_dw_church_intro1)
		roomname = stringsetsubloc("~1 - Atrium", church_name_a, "scr_roomname_slash_scr_roomname_gml_8_0_c")
	if (arg0 == room_dw_church_savepoint)
		roomname = stringsetsubloc("~1 - Lower Left", church_name_a, "scr_roomname_slash_scr_roomname_gml_9_0_c")
	if (arg0 == room_dw_church_ripplepuzzle_postgers)
		roomname = stringsetsubloc("~1 - Lower Right", church_name_a, "scr_roomname_slash_scr_roomname_gml_10_0")
	if (arg0 == room_dw_church_gersonstudy)
		roomname = stringsetsubloc("~1 - Study", church_name_a, "scr_roomname_slash_scr_roomname_gml_11_0_b")
	if (arg0 == room_dw_church_nwconnect)
		roomname = stringsetsubloc("~1 - Library", church_name_a, "scr_roomname_slash_scr_roomname_gml_12_0")
	if (arg0 == room_dw_church_pianopuzzle)
		roomname = stringsetsubloc("~1 - Small Piano", church_name_a, "scr_roomname_slash_scr_roomname_gml_13_0")
	var church_name_b = stringsetloc("2nd Sanctuary", "scr_roomname_slash_scr_roomname_gml_15_0")
	if (arg0 == room_dw_churchb_staircaseintro)
		roomname = stringsetsubloc("~1 - Atrium", church_name_b, "scr_roomname_slash_scr_roomname_gml_16_0")
	if (arg0 == room_dw_churchb_savepoint)
		roomname = stringsetsubloc("~1 - Floor", church_name_b, "scr_roomname_slash_scr_roomname_gml_17_0")
	if (arg0 == room_dw_churchb_gersonstudy)
		roomname = stringsetsubloc("~1 - Study", church_name_b, "scr_roomname_slash_scr_roomname_gml_18_0")
	if (arg0 == room_dw_churchb_darkclimb)
		roomname = stringsetsubloc("~1 - Study", church_name_b, "scr_roomname_slash_scr_roomname_gml_19_0")
	var church_name_c = stringsetloc("3rd Sanctuary", "scr_roomname_slash_scr_roomname_gml_21_0")
	if (arg0 == room_dw_churchc_superprophecies)
		roomname = church_name_c
	if (arg0 == room_dw_churchc_savepoint)
		roomname = stringsetsubloc("~1 - Stairs", church_name_c, "scr_roomname_slash_scr_roomname_gml_23_0")
	if (arg0 == room_dw_churchc_prepretitan)
		roomname = stringsetsubloc("~1 - Last Chamber", church_name_c, "scr_roomname_slash_scr_roomname_gml_24_0")
	if (arg0 == room_dw_castle_tv_zone_2)
		roomname = stringsetloc("MIKE ZONE", "scr_roomname_slash_scr_roomname_gml_29_0")
	if (arg0 == room_dw_castle_tv)
		roomname = stringsetloc("Castle Town - TV Building", "scr_roomname_slash_scr_roomname_gml_30_0")
	return roomname;
}
